{% set name = "stashy" %}
{% set version = "0.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9965aa18509b7576bbd4b068962d9a9a4828cec8ce22ee5a365ddbcebffa09f5

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python  =2.7|>=3.5
    - setuptools
  run:
    - decorator >=3.4.0
    - python  =2.7|>=3.5
    - requests >=2.5.1

test:
  imports:
    - stashy
    - stashy.admin

about:
  home: http://github.com/RisingOak/stashy
  license: Apache Software
  license_family: APACHE  
  license_file: LICENSE
  summary: Python API client for the Atlassian Stash REST API

extra:
  recipe-maintainers:
    - nicoddemus
