travis:
  secure:
    BINSTAR_TOKEN: fFV2/QIk44Rd804LJHiyX2Z1JDRP+TdAvPQb9E+w5Fes2KMlmFK6Gk+HEkFR75UGoILvSYy7LbK8hzS9vlwVLceR5Il4AJwEo0n8M+JJfo7k5VFQNwtJOO/BqMgJC+fyY20CS+V3YiX6gFl4Rowq+zUjNuRWFGf6ddMSc4y6A6eJHwaT/Xok7Dk1YUedaUky7XR42LIamkJ06OG9d/oarvJqbkkrF+hXJCmR1IwiYmETFn8LY65MZThGbzEeUccBt9FiZfwBFacDGI4WZ8B2ioHa2lVQqRmxb6qmzpKr1uTjSKP5nqSQNV+mjTCgVF3i8y2Ng83LNBeONA+4/Tj9PYRe02Gudjb347806IQFrsQ4bx4mnghPafXlRIwOdbAh5cEYPKz9c8Xit70KBq5bD+xky0TyQJYxfdDA673yhRMfNDVBH1SV5flmrCEU//WBJB6KU6EfAH0a0TXYvMRHJTUrtklYCMO6la+bKoJH7cqcZTi3piiBQrS0fhSyZaG1tMcKn28f4ucFhPxKXYRO9xKLoN1r+G5RS29n95jXjxyfzD66oSbaWqWAqglsdmZ+G1pY6Vms75JmrwgIVpEeEHBRkfr8v/qJ09tNDkIxLb2tL9ZXweFcabr8E1LNUk1rOnHmd6XhL6BX0rQvYDhO+ap0iaee4B/1LeAHYjgdc2k=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
