travis:
  secure:
    BINSTAR_TOKEN: pfWhASqLaxOOKquKXS/0Wu5yK2iNHhDDWhCZctin83F6/pubhk6OE56US+/44QDrkAIpLowe/pd1An4f9wcG8+wF5l08hOptSSZwIiuMK7lFaT3pb3x9VKK2bIA2yPU/CMu5m51MU+vfKevIB8Dufk6lJiI7T6kEkbijsumt+p8a4/uf4mbEGeCAbtYPSPwlpv4hBebU/i/ZUuKy6IdG5P74PImW6X+3tZHL+vu6TbnUpbeXyxmxc3nZThtvE0eip9OhBFrlCZ3up7ZGVtzXWkNhgTLOGylEOhHKcwX158mFlBqpeqz/9ovRbiuXl2u5VOTjtkD1b7enujDITwnqN3LIiXJ3+iquVwJDgj5Vg7udoLm2oKTH8oJGjDGK4jZZeI3KIfSR/NTSMn6+NsoVNbgk6oD1qe8SdmfYwl0hl0gvD4zhdYP/y8jN65KcvB226YGFRaYZrnilML1T/pWc3k2NcnIBNQTU3NH1MzmaPj9BA29TB4tZc9l0GzzZptJWzamtcenTI9hR7HizK9+aGWRS9FTw89exByfaNfjECu/zceRwSelxjzQLp+FXelpDDpdQJD0NywsCLVxnMcM6FV7hTtOuVIf+HF3m7dcQE34HoDcYU6780Bh+itA+oXz6lA1nq7qEI1BdhKz+kDTCarU/HRGYCoGRlL0WjPYolbA=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
